# Monthly Precipitation Data Cleaning – ECCC

This notebook performs data inspection, cleaning, and preparation of monthly precipitation data from Environment and Climate Change Canada (ECCC).

Scope of this notebook (Week 2):
- Monthly climate data
- Total Precipitation (mm)
- Nova Scotia weather stations
- Data wrangling and cleaning only (no analysis or modeling)

In [1]:
import pandas as pd
import numpy as np

In [2]:
# Load raw monthly climate data: Yarmouth station
file_path = "../Capstone/raw data/en_climate_monthly_NS_8206500_1940-2012_P1M_YARMOUTH.csv"
df_raw = pd.read_csv(file_path)

In [3]:
# Initial inspection of raw data
df_raw.head()
df_raw.info()
df_raw.describe(include="all")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 868 entries, 0 to 867
Data columns (total 29 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Longitude (x)               868 non-null    float64
 1   Latitude (y)                868 non-null    float64
 2   Station Name                868 non-null    object
 3   Climate ID                  868 non-null    int64
 4   Date/Time                   868 non-null    object
 5   Year                        868 non-null    int64
 6   Month                       868 non-null    int64
 7   Mean Max Temp (°C)          866 non-null    float64
 8   Mean Max Temp Flag          4 non-null      object
 9   Mean Min Temp (°C)          866 non-null    float64
 10  Mean Min Temp Flag          4 non-null      object
 11  Mean Temp (°C)              866 non-null    float64
 12  Mean Temp Flag              4 non-null      object
 13  Extr Max Temp (°C)          865 non-null    float64
 14  Extr Max Temp Flag          115 non-null    object
 15  Extr Min Temp (°C)          866 non-null    float64
 16  Extr Min Temp Flag          116 non-null    object
 17  Total Rain (mm)             862 non-null    float64
 18  Total Rain Flag             8 non-null      object
 19  Total Snow (cm)             863 non-null    float64
 20  Total Snow Flag             58 non-null     object
 21  Total Precip (mm)           862 non-null    float64
 22  Total Precip Flag           8 non-null      object
 23  Snow Grnd Last Day (cm)     685 non-null    float64
 24  Snow Grnd Last Day Flag     77 non-null     object
 25  Dir of Max Gust (10's deg)  658 non-null    float64
 26  Dir of Max Gust Flag        240 non-null    object
 27  Spd of Max Gust (km/h)      662 non-null    object
 28  Spd of Max Gust Flag        328 non-null    object
dtypes: float64(12), int64(3), object(14)
memory usage: 196.8+ KB

,Longitude (x),Latitude (y),Station Name,Climate ID,Date/Time,Year,Month,Mean Max Temp (°C),Mean Max Temp Flag,Mean Min Temp (°C),...,Total Snow (cm),Total Snow Flag,Total Precip (mm),Total Precip Flag,Snow Grnd Last Day (cm),Snow Grnd Last Day Flag,Dir of Max Gust (10's deg),Dir of Max Gust Flag,Spd of Max Gust (km/h),Spd of Max Gust Flag
count,8.680000e+02,8.680000e+02,868,868.0,868,868.000000,868.000000,866.000000,4,866.000000,...,863.000000,58,862.000000,8,685.000000,77,658.000000,240,662,328
unique,NaN,NaN,1,NaN,868,NaN,NaN,NaN,3,NaN,...,NaN,3,NaN,3,NaN,2,NaN,4,77,4
top,NaN,NaN,YARMOUTH A,NaN,1940-01,NaN,NaN,NaN,E,NaN,...,NaN,T,NaN,M,NaN,T,NaN,E,80,E
freq,NaN,NaN,868,NaN,1,NaN,NaN,NaN,2,NaN,...,NaN,53,NaN,5,NaN,52,NaN,183,31,240
mean,-6.609000e+01,4.383000e+01,NaN,8206500.0,NaN,1975.668203,6.481567,10.829677,NaN,3.153811,...,17.006141,NaN,107.105452,NaN,1.855474,NaN,20.939210,NaN,NaN,NaN
std,1.421905e-12,9.668952e-13,NaN,0.0,NaN,20.893547,3.457554,7.324455,NaN,6.912879,...,27.637396,NaN,52.309691,NaN,6.557739,NaN,8.950019,NaN,NaN,NaN
min,-6.609000e+01,4.383000e+01,NaN,8206500.0,NaN,1940.000000,1.000000,-3.800000,NaN,-10.700000,...,0.000000,NaN,5.600000,NaN,0.000000,NaN,1.000000,NaN,NaN,NaN
25%,-6.609000e+01,4.383000e+01,NaN,8206500.0,NaN,1958.000000,3.000000,3.800000,NaN,-3.300000,...,0.000000,NaN,69.600000,NaN,0.000000,NaN,14.000000,NaN,NaN,NaN
50%,-6.609000e+01,4.383000e+01,NaN,8206500.0,NaN,1976.000000,6.000000,11.100000,NaN,3.500000,...,0.000000,NaN,101.300000,NaN,0.000000,NaN,20.000000,NaN,NaN,NaN
75%,-6.609000e+01,4.383000e+01,NaN,8206500.0,NaN,1994.000000,9.000000,17.800000,NaN,9.575000,...,26.950000,NaN,138.575000,NaN,0.000000,NaN,29.000000,NaN,NaN,NaN
max,-6.609000e+01,4.383000e+01,NaN,8206500.0,NaN,2012.000000,12.000000,23.500000,NaN,14.600000,...,144.300000,NaN,381.500000,NaN,53.000000,NaN,36.000000,NaN,NaN,NaN

The raw dataset contains multiple climate variables.
For the purposes of Week 2, only the Total Precipitation (mm) field is retained to demonstrate data cleaning and preparation steps.

In [4]:
# Selecting relevant columns only
columns_to_keep = [
    "Year",
    "Month",
    "Total Precip (mm)"
]

df = df_raw[columns_to_keep].copy()
df.head()

   Year  Month  Total Precip (mm)
0  1940      1                NaN
1  1940      2                NaN
2  1940      3               80.8
3  1940      4              139.7
4  1940      5               56.4

In [5]:
# Rename columns for consistency and ease of use
df.columns = [
    "year",
    "month",
    "total_precip_mm"
]

In [6]:
# Data type cleaning
df["year"] = pd.to_numeric(df["year"], errors="coerce")
df["month"] = pd.to_numeric(df["month"], errors="coerce")
df["total_precip_mm"] = pd.to_numeric(df["total_precip_mm"], errors="coerce")

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 868 entries, 0 to 867
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   year             868 non-null    int64
 1   month            868 non-null    int64
 2   total_precip_mm  862 non-null    float64
dtypes: float64(1), int64(2)
memory usage: 20.5 KB

In [7]:
# Check missing values
df.isna().sum()

year               0
month              0
total_precip_mm    6
dtype: int64

In [8]:
# Remove records with missing precipitation or incomplete date information
df = df.dropna(subset=["year", "month", "total_precip_mm"])

# Convert year and month to integer after removing invalid values
df["year"] = df["year"].astype(int)
df["month"] = df["month"].astype(int)

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 862 entries, 2 to 867
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   year             862 non-null    int64
 1   month            862 non-null    int64
 2   total_precip_mm  862 non-null    float64
dtypes: float64(1), int64(2)
memory usage: 26.9 KB

In [9]:
# Check for duplicate records
df.duplicated().sum()

np.int64(0)

Records with missing precipitation values or incomplete date information were removed to produce a clean and consistent monthly dataset suitable for trend analysis. No duplicate values found.

In [10]:
# Basic outlier inspection for precipitation
df["total_precip_mm"].describe()

count    862.000000
mean     107.105452
std       52.309691
min        5.600000
25%       69.600000
50%      101.300000
75%      138.575000
max      381.500000
Name: total_precip_mm, dtype: float64

In [11]:
# Inspect extreme values using quantiles
df["total_precip_mm"].quantile([0.01, 0.99])

0.01     17.066
0.99    264.024
Name: total_precip_mm, dtype: float64

Potential outliers in monthly precipitation were inspected using summary statistics.
Extreme values were retained at this stage, as they may represent valid climatic events rather than data errors.
Outlier handling will be revisited during the analysis phase if required.

In [12]:
# Create a proper date field for temporal consistency
df["date"] = pd.to_datetime(
    df["year"].astype(str) + "-" + df["month"].astype(str) + "-01"
)

df.head()

   year  month  total_precip_mm       date
2  1940      3             80.8 1940-03-01
3  1940      4            139.7 1940-04-01
4  1940      5             56.4 1940-05-01
5  1940      6             85.9 1940-06-01
6  1940      7             59.4 1940-07-01

In [13]:
# Final inspection of cleaned dataset
df.info()

# Save cleaned dataset for further analysis and visualization
output_path = "../Capstone/clean data/precipitation_monthly_clean.csv"
df.to_csv(output_path, index=False)

output_path
df.head()

<class 'pandas.core.frame.DataFrame'>
Index: 862 entries, 2 to 867
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   year             862 non-null    int64
 1   month            862 non-null    int64
 2   total_precip_mm  862 non-null    float64
 3   date             862 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(2)
memory usage: 33.7 KB

   year  month  total_precip_mm       date
2  1940      3             80.8 1940-03-01
3  1940      4            139.7 1940-04-01
4  1940      5             56.4 1940-05-01
5  1940      6             85.9 1940-06-01
6  1940      7             59.4 1940-07-01

This cleaned dataset will be used in subsequent analysis and visualization steps.
Daily climate observations may be incorporated later to extend the time series beyond 2012 if required.